from django.db import models
from provider.models import Provider
from accountapp.models import User
from services.models import Service
from catagory.models import Catagory

# Create your models here.
class Booking(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]
    # id autogenerated
    user = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='bookings' ) # who will select
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings') # provider ,who is selecetd by user
    service = models.ForeignKey(Service , on_delete=models.CASCADE , related_name='bookings')
    # catagory = models.ForeignKey(Catagory , on_delete=models.CASCADE , related_name='bookings')
    catagory_name = models.CharField()
    scheduled_date = models.DateField()
    scheduled_time = models.TimeField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending',null=False)
    booked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Booking by {self.user.username} on {self.scheduled_date} for {self.service.name}"
