from django.db import models
from provider.models import Provider
from accountapp.models import User
from services.models import Service
from catagory.models import Catagory

# Create your models here.
class Booking(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]
    # id autogenerated
    customer = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='bookings' ) # who will select
    # provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings') # provider ,who is selecetd by user
    service = models.ForeignKey(Service , on_delete=models.CASCADE , related_name='bookings')
    catagory = models.ForeignKey(Catagory , on_delete=models.CASCADE , related_name='bookings')
    pincode = models.BigIntegerField(null=False)
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending',null=False)
    booked_at = models.DateTimeField(auto_now_add=True)

    provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings' ,default=None , null=True , blank=True) # provider ,who is selecetd by user

    def __str__(self):
        return f"Booking by {self.customer.username} -{self.service.name}"
