from django.db import models
from provider.models import Provider
from accountapp.models import User
from services.models import Service
from catagory.models import Catagory

# Create your models here.
class Booking(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]
    # id autogenerated
    customer = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='bookings' ) # who will select
    # provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings') # provider ,who is selecetd by user
    service = models.ForeignKey(Service , on_delete=models.CASCADE , related_name='bookings')
    catagory = models.ForeignKey(Catagory , on_delete=models.CASCADE , related_name='bookings')
    pincode = models.BigIntegerField(null=False)
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending',null=False)
    booked_at = models.DateTimeField(auto_now_add=True)

    provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings' ,default=None , null=True , blank=True) # provider ,who is selecetd by user
   
   #extra
    provider_contact = models.CharField(max_length=10)

    # customer     
    customer_contact=models.CharField(max_length=10)
    customer_address=models.TextField(max_length=225)
    
    def __str__(self):
        return f"customer-> {self.customer.username} provider-> {self.service.name}"
    
# class BookingDetails(models.Model): # GEt request
#     STATUS_CHOICES = [
#         ('pending', 'Pending'),
#         ('confirmed', 'Confirmed'),
#         ('completed', 'Completed'),
#         ('cancelled', 'Cancelled'),
#     ]
#     # customer details
#     customer = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='bookings' ) # who will select
#     full_name = models.CharField()
#     contact =models.CharField()
#     address =models.CharField()
#     pincode = models.BigIntegerField(null=False)

#     service = models.ForeignKey(Booking , on_delete=models.CASCADE , related_name='booking_details')
#     catagory = models.ForeignKey(Booking , on_delete=models.CASCADE , related_name='booking_details')
    
#     date = models.DateField()
#     time = models.TimeField()
#     status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending',null=False)
#     booked_at = models.DateTimeField(auto_now_add=True)

#     # provider details
#     provider = models.ForeignKey(Provider, on_delete=models.CASCADE , related_name='bookings' ,default=None , null=True , blank=True) # provider ,who is selecetd by user
#     experience =models.IntegerField()
#     chargesPerHour = models.DecimalField(max_digits=5, decimal_places=2)

    